### DO NOT USE FOR TRAIN, use tsinghua-ml instead
name: pii-detection-5090-cn
channels:
  # --- TSINGHUA MIRRORS ---
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
show_channel_urls: true
dependencies:
  - python=3.10
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - jupyterlab
  - scikit-learn
  - ipywidgets
  - spacy
  - pip 

  # --- PIP PACKAGES ---
  - pip:
    - -i https://pypi.tuna.tsinghua.edu.cn/simple
    - --extra-index-url https://download.pytorch.org/whl/nightly/cu128
    
    - --pre
    
    # 4. Core Dependencies
    - torch>=2.7.0.dev 
    - torchvision       
    - torchaudio
    
    # 5. Hugging Face & Training Stack
    - transformers==4.39.0
    - accelerate        
    - tokenizers
    - seqeval
    - sentencepiece
    - protobuf
    
    # 6. Utilities
    - kaggle
    - python-dotenv
    - tqdm
    - openai
    - faker
    - requests

    # allan metaclassifiers
    - xgboost