name: pii-detection-local
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  # --- CONDA PACKAGES ---
  - python=3.10
  - ipykernel
  - pytorch
  - cpuonly
  - numpy
  - pandas
  - matplotlib
  - jupyterlab
  - scikit-learn
  - ipywidgets
  - spacy
  
  # --- PIP PACKAGES ---
  - pip
  - pip:
    - kaggle
    - python-dotenv
    - tqdm
    - transformers
    - tokenizers
    - seqeval
    - openai
    - faker
    - gliner