"""Overrides tuned for RTX 5090 with 32GB VRAM."""

BATCH_SIZE = 64
GRADIENT_ACCUMULATION_STEPS = 1
GRADIENT_CHECKPOINTING = True
MAX_GRAD_NORM = 1.0

FP16 = False
BF16 = True

NUM_WORKERS = 6
EVAL_ACCUMULATION_STEPS = 4

LOGGING_STEPS = 25
SAVE_TOTAL_LIMIT = 1
SAVE_BEST_ONLY = True
SAVE_EVERY_N_EPOCHS = None
SAVE_ONLY_MODEL = True

TORCH_COMPILE = False
